install: true
script:
- git clone https://github.com/wgtdkp/apollonia
- ls -ahl
- tar czf apollonia.tar.gz --exclude "apollonia/demo/*" --exclude "*.pack" apollonia/
- ls -alh
#- find -type f -size +500k -exec ls -lh '{}' \;
#- find docs/en -type f -size +1024k -exec ls -lh '{}' \;
#- du -chs docs/en/*


deploy:
  skip_cleanup: true
  provider: releases
#  user: "beshkoon"
#  password: ""
  api_key: "${test2}"
  file: "../apollonia.tar.gz"
  on:
    tags: true
