install: true
script:
- git clone https://github.com/defold/doc
- ls -a
- cd doc
- tar czf ../defold_doc.tar.gz --exclude "*.png" docs/en/
- ls -alh ../
#- du -chs docs/en/*


deploy:
  skip_cleanup: true
  provider: releases
#  user: "beshkoon"
#  password: ""
  api_key: "${test2}"
  file: "../defold_doc.tar.gz"
#  on:
#    tags: true
