install: true
script:
- git clone https://github.com/defold/doc
- ls -a
- cd doc
- ls -a
- tar czf ../defold_doc.tar.gz docs/en
- ls -alh ../

deploy:
  skip_cleanup: true
  provider: releases
#  user: "beshkoon"
#  password: ""
  api_key: "${test2}"
  file: "../defold_doc.tar.gz"
#  on:
#    tags: true
