install: true
script:
- mkdir tst
- ls -ahl
- cd tst
- git clone https://github.com/libgdx/libgdx.wiki.git
- tar czf ../libgdx_wiki.tar.gz --exclude "*.png" *
- ls -alh ../
#- find docs/en -type f -size +1024k -exec ls -lh '{}' \;
#- du -chs docs/en/*


deploy:
  skip_cleanup: true
  provider: releases
#  user: "beshkoon"
#  password: ""
  api_key: "${test2}"
  file: "../libgdx_wiki.tar.gz"
#  on:
#    tags: true
