install: true
script:
- mkdir tst
- curl -o lbt.tar.gz "https://android.googlesource.com/platform/system/core/+archive/master/libbacktrace.tar.gz"
- cd tst
- tar xzf ../lbt.tar.gz
- tar czf ../libbacktrace.tar.gz *.*
#- find -type f -size +500k -exec ls -lh '{}' \;
#- du -chs docs/en/*


deploy:
  skip_cleanup: true
  provider: releases
#  user: "beshkoon"
#  password: ""
  api_key: "${test2}"
  file: "../libbacktrace.tar.gz"
  on:
    tags: true
